server:
  port: 4000

spring:
  application:
    name: ryun-supply-auth
  main:
    allow-bean-definition-overriding: true

  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

# feign 配置
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          timeout:
            enabled: true
          isolation:
            thread:
              timeoutInMilliseconds: 8000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ryun-supply-eureka:8761/eureka/

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
