server:
  port: 9999
    #  ssl证书相关配置
  ssl:
      key-store: classpath:https/2764629_wx_ryuntech_com.pfx
      key-store-password: 5vU1pYCw
      key-store-type: PKCS12

spring:
  application:
    name: ryuntech-su-cloud-gateway
  profiles:
    active: dev
  cloud:
    config:
      name: ${spring.application.name}
      profile: ${spring.profiles.active}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ryuntech-su-cloud-eureka:8761/eureka/

zuul:
  #需要忽略的头部信息，不在传播到其他服务
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  semaphore:
    max-semaphores: 100 # 默认值
  host:
    connections: 500
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000


