zuul:
  routes:
    ryun-supply-auth:
      path: /api/auth/**
      serviceId: ryun-supply-auth
    ryun-supply-admin:
      path: /api/admin/**
      serviceId: ryun-supply-admin-biz
#    ryun-supply-monitor:
#      path: /api/monitor/**
#      serviceId: ryun-supply-monitor
#    ryun-supply-zipkin:
#      path: /api/zipkin/**
#      serviceId: ryun-supply-zipkin
#    ryun-supply-eureka:
#      path: /api/eureka/**
#      serviceId: ryun-supply-eureka

